service: lambdas-poc
frameworkVersion: "3"
useDotenv: true

package:
  individually: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: nodejs16.x
  architecture: arm64
  deploymentBucket:
    name: doppler-fun-${sls:stage}

  httpApi:
    shouldStartNameWithService: true
    disableDefaultEndpoint: true
    metrics: true
    cors:
      allowedOrigins:
        - https://app.fromdoppler.com
        - https://app2.fromdoppler.com
        - https://appint.fromdoppler.net
        - https://appqa.fromdoppler.net
        - https://webappint.fromdoppler.net
        - https://webappqa.fromdoppler.net
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
      allowCredentials: true

  logs:
    httpApi: true

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: "arn:aws:dynamodb:${env:AWS_REGION}:${aws:accountId}:table\
            /${self:service}-${sls:stage}-customerTable"

  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-${sls:stage}-customerTable

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  createCustomer:
    handler: src/createCustomer.createCustomer
    events:
      - httpApi:
          path: /
          method: post
  getCustomers:
    handler: src/getCustomers.getCustomers
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-${sls:stage}-customerTable

custom:
  bundle:
    packager: "yarn"
    disableForkTsChecker: false
    linting: true
